from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from time import sleep
from selenium.webdriver.chrome.options import Options

from Locators import*
from Pages.Find_Element import FindElement
from Pages.Login import LoginPage
from Pages.Reports import Reports


import unittest

# o = Options()
# o.add_argument('--no-sandbox')
#
# s = Service('d:\chromedriver_win32\chromedriver.exe')
driver = webdriver.Chrome(ChromeDriverManager().install())
# driver = webdriver.Chrome(executable_path="E:\PRG_Test\Pinvest_Admin\chromedriver.exe")


class Test_Pinvest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.driver = driver
        # cls.driver = webdriver.Chrome(service=s, options=o)
        cls.driver.maximize_window()
        cls.driver.implicitly_wait(5)

    def test01_login_register(self):
        self.driver.get("https://admin-ha1.pinvest.ir/signin")
        login = LoginPage(driver=self.driver)
        login.enter_username("superadmin")
        login.enter_password("1234kaKA!")
        login.enter_show_password()
        login.enter_btn_submit()
        sleep(3)
        login.enter_site_header()
        # login.enter_logout()
        # login.enter_logout_no()
        # login.enter_logout()
        # login.enter_logout_yes()

# # # reports_sell_orders

    def test02_reports_sell_orders(self):
        reports= Reports(driver=self.driver)
        findel = FindElement(driver=self.driver)
        findel.wait_until_element_has_an_attribute('xpath', click_reports, 'class', 'cursor_pointer')
        # reports.enter_click_reports()
        findel.wait_until_element_has_an_attribute('xpath', click_reports_sell_orders, 'class', '/reports/sell-orders')
        # reports.enter_click_reports_sell_orders()
        # assert reports
        reports.enter_reports_sell_orders_assert()
        reports.enter_reports_sell_orders_from_date()
        reports.enter_reports_sell_orders_from_date_back()
        reports.enter_reports_sell_orders_from_date_option()
        reports.enter_reports_sell_orders_to_date()
        reports.enter_reports_sell_orders_to_date_next()
        reports.enter_reports_sell_orders_to_date_option()
        reports.enter_reports_sell_orders_type()
        reports.enter_reports_sell_orders_type_option()
        reports.enter_reports_sell_orders_fund()
        reports.enter_reports_sell_orders_fund_option()
        reports.enter_reports_sell_orders_status()
        reports.enter_reports_sell_orders_status_option()
        reports.enter_reports_sell_orders_method()
        reports.enter_reports_sell_orders_method_option()
        reports.enter_reports_sell_orders_search("4120")
        # sleep(2)
        # reports.enter_reports_sell_orders_result()
        # self.driver.refresh()

# # # reports_cms_sell_orders

    def test03_reports_cms_sell_orders(self):
        reports = Reports(driver=self.driver)
        findel = FindElement(driver=self.driver)
        # sleep(1)
        # findel.wait_until_element_has_an_attribute('xpath', click_reports, 'class', 'cursor_pointer')
        # reports.enter_click_reports()
        # sleep(1)
        findel.wait_until_element_has_an_attribute('xpath', click_reports_cms_sell_orders, 'href', '/reports/cms')
        # reports.enter_click_reports_cms_sell_orders()
        # assert reports
        reports.enter_reports_cms_sell_orders_assert()
        reports.enter_reports_cms_sell_orders_from_date()
        reports.enter_reports_cms_sell_orders_from_date_back()
        reports.enter_reports_cms_sell_orders_from_date_option()
        reports.enter_reports_cms_sell_orders_to_date()
        reports.enter_reports_cms_sell_orders_to_date_next()
        reports.enter_reports_cms_sell_orders_to_date_option()
        reports.enter_reports_cms_sell_orders_type()
        reports.enter_reports_cms_sell_orders_type_option()
        reports.enter_reports_cms_sell_orders_status()
        reports.enter_reports_cms_sell_orders_status_option()
        # reports.enter_reports_cms_sell_orders_search("4120")
        print("گزارشات کاربران:")
        sleep(1)
        reports.enter_reports_cms_sell_orders_result()

    def test04_reports_shaba(self):
        reports = Reports(driver=self.driver)
        reports.enter_reports_cms_sell_orders_shaba()
        print("اطلاعات شبا یک کاربر:")
        reports.enter_reports_cms_sell_orders_shaba_result()

# # # reports_superAdmin

    def test05_reports_superAdmin(self):
        reports = Reports(driver=self.driver)
        findel = FindElement(driver=self.driver)
        # findel.wait_until_element_has_an_attribute('xpath', click_reports, 'class', 'cursor_pointer')
        # reports.enter_click_reports()
        # sleep(1)
        # findel.wait_until_element_has_an_attribute('xpath', click_reports_superAdmin, 'href', '/reports/superAdmin')
        reports.enter_click_reports_superAdmin()
        # assert reports
        reports.enter_reports_superAdmin_assert()
        reports.enter_reports_superAdmin_value_report_1()
        reports.enter_reports_superAdmin_value_report_2()
        reports.enter_reports_superAdmin_value_report_3()
        reports.enter_reports_superAdmin_value_report_4()
        reports.enter_reports_superAdmin_report_4_month()
        reports.enter_reports_superAdmin_report_4_month_option()
        reports.enter_reports_superAdmin_report_4_year()
        reports.enter_reports_superAdmin_report_4_year_option()
        reports.enter_reports_superAdmin_report_4_graph()
        reports.enter_reports_superAdmin_report_4_graph()
        vw = self.driver.find_element('xpath', "//*[@id='value_report_7']")
        vw.location_once_scrolled_into_view
        reports.enter_reports_superAdmin_value_report_5()
        reports.enter_reports_superAdmin_report_5_month()
        reports.enter_reports_superAdmin_report_5_month_option()
        reports.enter_reports_superAdmin_report_5_year()
        reports.enter_reports_superAdmin_report_5_year_option()
        findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_5_graph, 'class', 'icon pi-account-reports show_chart')
        findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_5_graph, 'class', 'icon pi-account-reports show_chart')
        # reports.enter_reports_superAdmin_report_5_graph()
        # reports.enter_reports_superAdmin_report_5_graph()
        reports.enter_reports_superAdmin_value_report_6()
        findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_6_month, 'class', 'form-select form-select-sm month_select')
        # reports.enter_reports_superAdmin_report_6_month()
        reports.enter_reports_superAdmin_report_6_month_option()
        findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_6_year, 'class', 'form-select form-select-sm year_select')
        # reports.enter_reports_superAdmin_report_6_year()
        reports.enter_reports_superAdmin_report_6_year_option()
        findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_6_graph, 'class', 'icon pi-account-reports show_chart')
        findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_6_graph, 'class', 'icon pi-account-reports show_chart')
        # reports.enter_reports_superAdmin_report_6_graph()
        # reports.enter_reports_superAdmin_report_6_graph()
        vw2 = self.driver.find_element('xpath', "//*[@id='value_report_9']")
        vw2.location_once_scrolled_into_view
        reports.enter_reports_superAdmin_value_report_7()
        findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_7_month, 'class', 'form-select form-select-sm month_select')
        # reports.enter_reports_superAdmin_report_7_month()
        reports.enter_reports_superAdmin_report_7_month_option()
        findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_7_year, 'class', 'form-select form-select-sm year_select')
        # reports.enter_reports_superAdmin_report_7_year()
        reports.enter_reports_superAdmin_report_7_year_option()
        findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_7_graph, 'class', 'icon pi-account-reports show_chart')
        findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_7_graph, 'class', 'icon pi-account-reports show_chart')
        # reports.enter_reports_superAdmin_report_7_graph()
        # reports.enter_reports_superAdmin_report_7_graph()
        reports.enter_reports_superAdmin_value_report_8()
        findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_8_month, 'class', 'form-select form-select-sm month_select')
        # reports.enter_reports_superAdmin_report_8_month()
        reports.enter_reports_superAdmin_report_8_month_option()
        findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_8_year, 'class', 'form-select form-select-sm year_select')
        # reports.enter_reports_superAdmin_report_8_year()
        reports.enter_reports_superAdmin_report_8_year_option()
        findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_8_graph, 'class', 'icon pi-account-reports show_chart')
        findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_8_graph, 'class', 'icon pi-account-reports show_chart')
        # reports.enter_reports_superAdmin_report_8_graph()
        # reports.enter_reports_superAdmin_report_8_graph()
        reports.enter_reports_superAdmin_value_report_9()
        findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_9_month, 'class', 'form-select form-select-sm month_select')
        # reports.enter_reports_superAdmin_report_9_month()
        reports.enter_reports_superAdmin_report_9_month_option()
        findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_9_year, 'class', 'form-select form-select-sm year_select')
        # reports.enter_reports_superAdmin_report_9_year()
        reports.enter_reports_superAdmin_report_9_year_option()
        findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_9_graph, 'class', 'icon pi-account-reports show_chart')
        findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_9_graph, 'class', 'icon pi-account-reports show_chart')
        # reports.enter_reports_superAdmin_report_9_graph()
        # reports.enter_reports_superAdmin_report_9_graph()
        vw2 = self.driver.find_element('xpath', "//*[@id='value_report_13']")
        vw2.location_once_scrolled_into_view
        reports.enter_reports_superAdmin_value_report_10()
        findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_10_month, 'class', 'form-select form-select-sm month_select')
        # reports.enter_reports_superAdmin_report_10_month()
        reports.enter_reports_superAdmin_report_10_month_option()
        findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_10_year, 'class', 'form-select form-select-sm year_select')
        # reports.enter_reports_superAdmin_report_10_year()
        reports.enter_reports_superAdmin_report_10_year_option()
        # findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_10_graph, 'class', 'icon pi-account-reports show_chart')
        # findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_10_graph, 'class', 'icon pi-account-reports show_chart')
        # reports.enter_reports_superAdmin_report_10_graph()
        # reports.enter_reports_superAdmin_report_10_graph()
        # findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_10_fund, 'class', 'icon pi-faq show_data')
        # reports.enter_reports_superAdmin_report_10_fund()
        # reports.enter_reports_superAdmin_report_10_fund_result()
        # reports.enter_reports_superAdmin_report_10_fund()
        reports.enter_reports_superAdmin_value_report_11()
        findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_11_month, 'class', 'form-select form-select-sm month_select')
        # reports.enter_reports_superAdmin_report_11_month()
        reports.enter_reports_superAdmin_report_11_month_option()
        findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_11_year, 'class', 'form-select form-select-sm year_select')
        # reports.enter_reports_superAdmin_report_11_year()
        reports.enter_reports_superAdmin_report_11_year_option()
        findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_11_graph, 'class', 'icon pi-account-reports show_chart')
        # reports.enter_reports_superAdmin_report_11_graph()
        # reports.enter_reports_superAdmin_report_11_graph()
        findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_11_fund, 'class', 'icon pi-faq show_data')
        reports.enter_reports_superAdmin_report_11_fund_result()
        findel.wait_until_element_has_an_attribute('xpath', reports_superAdmin_report_11_fund, 'class', 'icon pi-faq show_data')
        # reports.enter_reports_superAdmin_value_report_12()
        # reports.enter_reports_superAdmin_report_12_month()
        # # reports.enter_reports_superAdmin_report_12_month_option()
        # reports.enter_reports_superAdmin_report_12_year()
        # reports.enter_reports_superAdmin_report_12_year_option()
        # reports.enter_reports_superAdmin_report_12_graph()
        # reports.enter_reports_superAdmin_report_12_graph()
        # reports.enter_reports_superAdmin_report_12_fund()
        # sleep(1)
        # reports.enter_reports_superAdmin_report_12_fund_result()
        # reports.enter_reports_superAdmin_report_12_fund()
        # reports.enter_reports_superAdmin_value_report_13()
        # reports.enter_reports_superAdmin_report_13_month()
        # # reports.enter_reports_superAdmin_report_13_month_option()
        # reports.enter_reports_superAdmin_report_13_year()
        # reports.enter_reports_superAdmin_report_13_year_option()
        # reports.enter_reports_superAdmin_report_13_graph()
        # reports.enter_reports_superAdmin_report_13_graph()
        # reports.enter_reports_superAdmin_report_13_fund()
        # sleep(1)
        # reports.enter_reports_superAdmin_report_13_fund_result()
        # reports.enter_reports_superAdmin_report_13_fund()
        # reports.enter_reports_superAdmin_value_report_14()
        # reports.enter_reports_superAdmin_report_14_month()
        # # reports.enter_reports_superAdmin_report_14_month_option()
        # reports.enter_reports_superAdmin_report_14_year()
        # reports.enter_reports_superAdmin_report_14_year_option()
        # reports.enter_reports_superAdmin_report_14_graph()
        # reports.enter_reports_superAdmin_report_14_graph()
        # reports.enter_reports_superAdmin_report_14_fund()
        # sleep(1)
        # reports.enter_reports_superAdmin_report_14_fund_result()
        # reports.enter_reports_superAdmin_report_14_fund()
        # reports.enter_reports_superAdmin_value_report_15()
        # reports.enter_reports_superAdmin_report_15_month()
        # # reports.enter_reports_superAdmin_report_15_month_option()
        # reports.enter_reports_superAdmin_report_15_year()
        # reports.enter_reports_superAdmin_report_15_year_option()
        # reports.enter_reports_superAdmin_report_15_graph()
        # reports.enter_reports_superAdmin_report_15_graph()
        # reports.enter_reports_superAdmin_report_15_fund()
        # sleep(1)
        # reports.enter_reports_superAdmin_report_15_fund_result()
        # reports.enter_reports_superAdmin_report_15_fund()
        # reports.enter_reports_superAdmin_value_report_16()
        # reports.enter_reports_superAdmin_report_16_month()
        # # reports.enter_reports_superAdmin_report_16_month_option()
        # reports.enter_reports_superAdmin_report_16_year()
        # reports.enter_reports_superAdmin_report_16_year_option()
        # reports.enter_reports_superAdmin_report_16_graph()
        # reports.enter_reports_superAdmin_report_16_graph()
        # reports.enter_reports_superAdmin_report_16_fund()
        # sleep(1)
        # reports.enter_reports_superAdmin_report_16_fund_result()
        # reports.enter_reports_superAdmin_report_16_fund()
        # reports.enter_reports_superAdmin_value_report_17()
        # reports.enter_reports_superAdmin_report_17_month()
        # # reports.enter_reports_superAdmin_report_17_month_option()
        # reports.enter_reports_superAdmin_report_17_year()
        # reports.enter_reports_superAdmin_report_17_year_option()
        # reports.enter_reports_superAdmin_report_17_graph()
        # reports.enter_reports_superAdmin_report_17_graph()
        # reports.enter_reports_superAdmin_report_17_fund()
        # sleep(1)
        # reports.enter_reports_superAdmin_report_17_fund_result()
        # reports.enter_reports_superAdmin_report_17_fund()
        # reports.enter_reports_superAdmin_value_report_18()
        # reports.enter_reports_superAdmin_report_18_month()
        # # reports.enter_reports_superAdmin_report_18_month_option()
        # reports.enter_reports_superAdmin_report_18_year()
        # reports.enter_reports_superAdmin_report_18_year_option()
        # reports.enter_reports_superAdmin_report_18_graph()
        # reports.enter_reports_superAdmin_report_18_graph()
        # reports.enter_reports_superAdmin_report_18_fund()
        # sleep(1)
        # reports.enter_reports_superAdmin_report_18_fund_result()
        # reports.enter_reports_superAdmin_report_18_fund()
        # reports.enter_reports_superAdmin_value_report_19()
        # reports.enter_reports_superAdmin_report_19_month()
        # # reports.enter_reports_superAdmin_report_19_month_option()
        # reports.enter_reports_superAdmin_report_19_year()
        # reports.enter_reports_superAdmin_report_19_year_option()
        # reports.enter_reports_superAdmin_report_19_graph()
        # reports.enter_reports_superAdmin_report_19_graph()
        # reports.enter_reports_superAdmin_report_19_fund()
        # sleep(1)
        # reports.enter_reports_superAdmin_report_19_fund_result()
        # reports.enter_reports_superAdmin_report_19_fund()
        # reports.enter_reports_superAdmin_value_report_20()
        # reports.enter_reports_superAdmin_report_20_month()
        # # reports.enter_reports_superAdmin_report_20_month_option()
        # reports.enter_reports_superAdmin_report_20_year()
        # reports.enter_reports_superAdmin_report_20_year_option()
        # reports.enter_reports_superAdmin_report_20_graph()
        # reports.enter_reports_superAdmin_report_20_graph()
        # reports.enter_reports_superAdmin_report_20_fund()
        # sleep(1)
        # reports.enter_reports_superAdmin_report_20_fund_result()
        # reports.enter_reports_superAdmin_report_20_fund()
        # reports.enter_reports_superAdmin_value_report_21()
        # reports.enter_reports_superAdmin_report_21_month()
        # # reports.enter_reports_superAdmin_report_21_month_option()
        # reports.enter_reports_superAdmin_report_21_year()
        # reports.enter_reports_superAdmin_report_21_year_option()
        # reports.enter_reports_superAdmin_report_21_graph()
        # reports.enter_reports_superAdmin_report_21_graph()
        # reports.enter_reports_superAdmin_report_21_fund()
        # sleep(1)
        # reports.enter_reports_superAdmin_report_21_fund_result()
        # reports.enter_reports_superAdmin_report_21_fund()
        # reports.enter_reports_superAdmin_value_report_22()
        # reports.enter_reports_superAdmin_report_22_month()
        # # reports.enter_reports_superAdmin_report_22_month_option()
        # reports.enter_reports_superAdmin_report_22_year()
        # reports.enter_reports_superAdmin_report_22_year_option()
        # reports.enter_reports_superAdmin_report_22_graph()
        # reports.enter_reports_superAdmin_report_22_graph()
        # reports.enter_reports_superAdmin_report_22_fund()
        # sleep(1)
        # reports.enter_reports_superAdmin_report_22_fund_result()
        # reports.enter_reports_superAdmin_report_22_fund()

# # # reports_providers

    def test06_reports_providers(self):
        reports = Reports(driver=self.driver)
        findel = FindElement(driver=self.driver)
        # findel.wait_until_element_has_an_attribute('xpath', click_reports, 'class', 'cursor_pointer')
        # reports.enter_click_reports()
        # sleep(1)
        findel.wait_until_element_has_an_attribute('xpath', click_reports_providers, 'href', '/reports/providers')
        # reports.enter_click_reports_providers()
        # assert reports
        reports.enter_reports_providers_assert()
        reports.enter_reports_providers_value_report_1()
        reports.enter_reports_providers_report_1_month()
        # reports.enter_reports_providers_report_1_month_option()
        reports.enter_reports_providers_report_1_year()
        reports.enter_reports_providers_report_1_year_option()
        reports.enter_reports_providers_report_1_graph()
        reports.enter_reports_providers_report_1_graph()
        reports.enter_reports_providers_report_1_fund()
        sleep(1)
        reports.enter_reports_providers_report_1_fund_result()
        reports.enter_reports_providers_report_1_fund()
        reports.enter_reports_providers_value_report_2()
        reports.enter_reports_providers_report_2_month()
        # reports.enter_reports_providers_report_2_month_option()
        reports.enter_reports_providers_report_2_year()
        reports.enter_reports_providers_report_2_year_option()
        reports.enter_reports_providers_report_2_graph()
        reports.enter_reports_providers_report_2_graph()
        reports.enter_reports_providers_report_2_fund()
        sleep(1)
        reports.enter_reports_providers_report_2_fund_result()
        reports.enter_reports_providers_report_2_fund()

# # # reports_cards_daily

    def test07_reports_cards_daily(self):
        reports = Reports(driver=self.driver)
        findel = FindElement(driver=self.driver)
        # findel.wait_until_element_has_an_attribute('xpath', click_reports, 'class', 'cursor_pointer')
        # reports.enter_click_reports()
        findel.wait_until_element_has_an_attribute('xpath', click_reports_cards_daily, 'href', '/reports/cards-daily')
        # reports.enter_click_reports_cards_daily()
        # assert reports
        reports.enterreports_cards_daily_assert()
        reports.enter_reports_cards_daily_date()
        # reports.enter_reports_cards_daily_date_back()
        reports.enter_reports_cards_daily_date_option()
        # sleep(1)
        # reports.enter_reports_cards_daily_result()

# # # reports_users_invited_phone_search

    def test08_reports_users_invited_phone_search(self):
        reports = Reports(driver=self.driver)
        findel = FindElement(driver=self.driver)
        # findel.wait_until_element_has_an_attribute('xpath', click_reports, 'class', 'cursor_pointer')
        # reports.enter_click_reports()
        findel.wait_until_element_has_an_attribute('xpath', click_reports_users_invited, 'href', '/reports/users-invited')
        # reports.enter_click_reports_users_invited()
        # assert reports
        reports.enter_reports_users_invited_assert()
        reports.enter_reports_users_invited_phone_search("4120")
        reports.enter_reports_users_invited_from_date()
        reports.enter_reports_users_invited_from_date_back()
        reports.enter_reports_users_invited_from_date_option()
        reports.enter_reports_users_invited_to_date()
        reports.enter_reports_users_invited_to_date_next()
        reports.enter_reports_users_invited_to_date_option()
        sleep(1)
        reports.enter_reports_users_invited_phone_search_result()

# # # reports_users_invited_phone_search

    def test09_enter_reports_users_invited_name_search(self):
        reports = Reports(driver=self.driver)
        self.driver.refresh()
        reports.enter_reports_users_invited_name_search("کیانوش")
        sleep(1)
        reports.enter_reports_users_invited_phone_search_result()

# # # reports_users_buy_sell_phone_search

    def test10_reports_users_buy_phone_search(self):
        reports = Reports(driver=self.driver)
        findel = FindElement(driver=self.driver)
        # findel.wait_until_element_has_an_attribute('xpath', click_reports, 'class', 'cursor_pointer')
        # reports.enter_click_reports()
        findel.wait_until_element_has_an_attribute('xpath', click_reports_users_buy_sell, 'href', '/reports/users-buy-sell')
        # reports.enter_click_reports_users_buy_sell()
        # assert reports
        reports.enter_reports_users_buy_sell_assert()
        reports.enter_reports_users_buy_sell_phone_search("4120")
        reports.enter_reports_users_buy_sell_from_date()
        reports.enter_reports_users_buy_sell_from_date_back()
        reports.enter_reports_users_buy_sell_from_date_option()
        reports.enter_reports_users_buy_sell_to_date()
        reports.enter_reports_users_buy_sell_to_date_next()
        reports.enter_reports_users_buy_sell_to_date_option()
        sleep(1)
        reports.enter_reports_users_buy_sell_phone_search_result()

# # # reports_users_sell_phone_search

    def test11_reports_users_sell_phone_search(self):
        reports = Reports(driver=self.driver)
        reports.enter_reports_users_buy_sell_btn_sale()
        sleep(1)
        reports.enter_reports_users_buy_sell_phone_search_result()

# # # reports_users_buy_sell_name_search

    def test12_reports_users_buy_sell_name_search(self):
        reports = Reports(driver=self.driver)
        self.driver.refresh()
        reports.enter_reports_users_buy_sell_name_search("h.soleimani")
        # sleep(2)
        # reports.enter_reports_users_buy_sell_phone_search_result()

# # # reports_users_sell_name_search

    def test13_reports_users_sell_name_search(self):
        reports = Reports(driver=self.driver)
        reports.enter_reports_users_buy_sell_btn_sale()
        sleep(1)
        reports.enter_reports_users_buy_sell_phone_search_result()

# # # reports_disabled_accounts

    def test14_reports_disabled_accounts(self):
        reports = Reports(driver=self.driver)
        findel = FindElement(driver=self.driver)
        # findel.wait_until_element_has_an_attribute('xpath', click_reports, 'class', 'cursor_pointer')
        # reports.enter_click_reports()
        findel.wait_until_element_has_an_attribute('xpath', click_reports_disabled_accounts, 'href', '/reports/disabled-accounts')
        # reports.enter_click_reports_disabled_accounts()
        # assert reports
        reports.enter_reports_disabled_accounts_assert()
        reports.enter_reports_disabled_accounts_phone_search("412")
        reports.enter_reports_disabled_accounts_from_date()
        reports.enter_reports_disabled_accounts_from_date_back()
        reports.enter_reports_disabled_accounts_from_date_option()
        reports.enter_reports_disabled_accounts_to_date()
        reports.enter_reports_disabled_accounts_to_date_next()
        reports.enter_reports_disabled_accounts_to_date_option()
        sleep(1)
        reports.enter_reports_disabled_accounts_phone_search_result()

    @classmethod
    def tearDownClass(cls) -> None:
        sleep(5)
        cls.driver.close()
        cls.driver.quit()
