from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from time import sleep
from selenium.webdriver.chrome.options import Options

from Locators import click_reports, click_reports_superAdmin
from Pages.Find_Element import FindElement
from Pages.Login import LoginPage
from Pages.Reports import Reports


import unittest

# o = Options()
# o.add_argument('--no-sandbox')
#
# s = Service('d:\chromedriver_win32\chromedriver.exe')
driver = webdriver.Chrome(ChromeDriverManager().install())
# driver = webdriver.Chrome(executable_path="E:\PRG_Test\Pinvest_Admin\chromedriver.exe")


class Test_Pinvest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.driver = driver
        # cls.driver = webdriver.Chrome(service=s, options=o)
        cls.driver.maximize_window()
        # cls.driver.minimize_window()
        cls.driver.implicitly_wait(10)

    def test01_login_register(self):
        self.driver.get("https://admin-ha1.pinvest.ir/signin")
        findel = FindElement(driver=self.driver)
        login = LoginPage(driver=self.driver)
        login.enter_username("superadmin")
        login.enter_password("1234kaKA!")
        login.enter_show_password()
        login.enter_btn_submit()
        # sleep(3)
        findel.lod_page()
        # navigationStart = driver.execute_script("return window.performance.timing.navigationStart")
        # responseStart = driver.execute_script("return window.performance.timing.responseStart")
        # domComplete = driver.execute_script("return window.performance.timing.domComplete")
        #
        # ''' Calculate the performance'''
        # backendPerformance_calc = responseStart - navigationStart
        # frontendPerformance_calc = domComplete - responseStart
        #
        # print( "Front End:", frontendPerformance_calc,"Back End:", backendPerformance_calc)

        login.enter_site_header()
        # login.enter_logout()
        # login.enter_logout_no()
        # login.enter_logout()
        # login.enter_logout_yes()

# # # reports_superAdmin

    def test02_reports_superAdmin(self):
        reports = Reports(driver=self.driver)
        findel = FindElement(driver=self.driver)
        findel.wait_until_element_has_an_attribute('xpath', click_reports, 'class', 'cursor_pointer')
        # reports.enter_click_reports()
        # sleep(1)
        findel.wait_until_element_has_an_attribute('xpath', click_reports_superAdmin, 'href', '/reports/superAdmin')
        # reports.enter_click_reports_superAdmin()
        # assert reports
        findel.lod_page()
        reports.enter_reports_superAdmin_assert()
        reports.enter_reports_superAdmin_value_report_1()
        reports.enter_reports_superAdmin_value_report_2()
        reports.enter_reports_superAdmin_value_report_3()
        reports.enter_reports_superAdmin_value_report_4()
        reports.enter_reports_superAdmin_report_4_month()
        reports.enter_reports_superAdmin_report_4_month_option()
        reports.enter_reports_superAdmin_report_4_year()
        reports.enter_reports_superAdmin_report_4_year_option()
        reports.enter_reports_superAdmin_report_4_graph()
        reports.enter_reports_superAdmin_report_4_graph()
        vw= self.driver.find_element('xpath', "//*[@id='value_report_7']")
        vw.location_once_scrolled_into_view
        reports.enter_reports_superAdmin_value_report_5()
        reports.enter_reports_superAdmin_report_5_month()
        reports.enter_reports_superAdmin_report_5_month_option()
        reports.enter_reports_superAdmin_report_5_year()
        reports.enter_reports_superAdmin_report_5_year_option()
        reports.enter_reports_superAdmin_report_5_graph()
        reports.enter_reports_superAdmin_report_5_graph()
        reports.enter_reports_superAdmin_value_report_6()
        reports.enter_reports_superAdmin_report_6_month()
        reports.enter_reports_superAdmin_report_6_month_option()
        reports.enter_reports_superAdmin_report_6_year()
        reports.enter_reports_superAdmin_report_6_year_option()
        reports.enter_reports_superAdmin_report_6_graph()
        reports.enter_reports_superAdmin_report_6_graph()
        vw2= self.driver.find_element('xpath', "//*[@id='value_report_9']")
        vw2.location_once_scrolled_into_view
        reports.enter_reports_superAdmin_value_report_7()
        reports.enter_reports_superAdmin_report_7_month()
        reports.enter_reports_superAdmin_report_7_month_option()
        reports.enter_reports_superAdmin_report_7_year()
        reports.enter_reports_superAdmin_report_7_year_option()
        reports.enter_reports_superAdmin_report_7_graph()
        reports.enter_reports_superAdmin_report_7_graph()
        reports.enter_reports_superAdmin_value_report_8()
        reports.enter_reports_superAdmin_report_8_month()
        reports.enter_reports_superAdmin_report_8_month_option()
        reports.enter_reports_superAdmin_report_8_year()
        reports.enter_reports_superAdmin_report_8_year_option()
        reports.enter_reports_superAdmin_report_8_graph()
        reports.enter_reports_superAdmin_report_8_graph()
        reports.enter_reports_superAdmin_value_report_9()
        reports.enter_reports_superAdmin_report_9_month()
        reports.enter_reports_superAdmin_report_9_month_option()
        reports.enter_reports_superAdmin_report_9_year()
        reports.enter_reports_superAdmin_report_9_year_option()
        reports.enter_reports_superAdmin_report_9_graph()
        reports.enter_reports_superAdmin_report_9_graph()
        vw2= self.driver.find_element('xpath', "//*[@id='value_report_13']")
        vw2.location_once_scrolled_into_view
        reports.enter_reports_superAdmin_value_report_10()
        reports.enter_reports_superAdmin_report_10_month()
        reports.enter_reports_superAdmin_report_10_month_option()
        reports.enter_reports_superAdmin_report_10_year()
        reports.enter_reports_superAdmin_report_10_year_option()
        reports.enter_reports_superAdmin_report_10_graph()
        reports.enter_reports_superAdmin_report_10_graph()
        reports.enter_reports_superAdmin_report_10_fund()
        reports.enter_reports_superAdmin_report_10_fund_result()
        reports.enter_reports_superAdmin_report_10_fund()
        reports.enter_reports_superAdmin_value_report_11()
        reports.enter_reports_superAdmin_report_11_month()
        reports.enter_reports_superAdmin_report_11_month_option()
        reports.enter_reports_superAdmin_report_11_year()
        reports.enter_reports_superAdmin_report_11_year_option()
        reports.enter_reports_superAdmin_report_11_graph()
        reports.enter_reports_superAdmin_report_11_graph()
        reports.enter_reports_superAdmin_value_report_12()
        reports.enter_reports_superAdmin_report_12_month()
        # reports.enter_reports_superAdmin_report_12_month_option()
        reports.enter_reports_superAdmin_report_12_year()
        reports.enter_reports_superAdmin_report_12_year_option()
        reports.enter_reports_superAdmin_report_12_graph()
        reports.enter_reports_superAdmin_report_12_graph()
        reports.enter_reports_superAdmin_report_12_fund()
        sleep(1)
        reports.enter_reports_superAdmin_report_12_fund_result()
        reports.enter_reports_superAdmin_report_12_fund()
        reports.enter_reports_superAdmin_value_report_13()
        reports.enter_reports_superAdmin_report_13_month()
        # reports.enter_reports_superAdmin_report_13_month_option()
        reports.enter_reports_superAdmin_report_13_year()
        reports.enter_reports_superAdmin_report_13_year_option()
        reports.enter_reports_superAdmin_report_13_graph()
        reports.enter_reports_superAdmin_report_13_graph()
        reports.enter_reports_superAdmin_report_13_fund()
        sleep(1)
        reports.enter_reports_superAdmin_report_13_fund_result()
        reports.enter_reports_superAdmin_report_13_fund()
        reports.enter_reports_superAdmin_value_report_14()
        reports.enter_reports_superAdmin_report_14_month()
        # reports.enter_reports_superAdmin_report_14_month_option()
        reports.enter_reports_superAdmin_report_14_year()
        reports.enter_reports_superAdmin_report_14_year_option()
        reports.enter_reports_superAdmin_report_14_graph()
        reports.enter_reports_superAdmin_report_14_graph()
        reports.enter_reports_superAdmin_report_14_fund()
        sleep(1)
        reports.enter_reports_superAdmin_report_14_fund_result()
        reports.enter_reports_superAdmin_report_14_fund()
        reports.enter_reports_superAdmin_value_report_15()
        reports.enter_reports_superAdmin_report_15_month()
        # reports.enter_reports_superAdmin_report_15_month_option()
        reports.enter_reports_superAdmin_report_15_year()
        reports.enter_reports_superAdmin_report_15_year_option()
        reports.enter_reports_superAdmin_report_15_graph()
        reports.enter_reports_superAdmin_report_15_graph()
        reports.enter_reports_superAdmin_report_15_fund()
        sleep(1)
        reports.enter_reports_superAdmin_report_15_fund_result()
        reports.enter_reports_superAdmin_report_15_fund()
        reports.enter_reports_superAdmin_value_report_16()
        reports.enter_reports_superAdmin_report_16_month()
        # reports.enter_reports_superAdmin_report_16_month_option()
        reports.enter_reports_superAdmin_report_16_year()
        reports.enter_reports_superAdmin_report_16_year_option()
        reports.enter_reports_superAdmin_report_16_graph()
        reports.enter_reports_superAdmin_report_16_graph()
        reports.enter_reports_superAdmin_report_16_fund()
        sleep(1)
        reports.enter_reports_superAdmin_report_16_fund_result()
        reports.enter_reports_superAdmin_report_16_fund()
        reports.enter_reports_superAdmin_value_report_17()
        reports.enter_reports_superAdmin_report_17_month()
        # reports.enter_reports_superAdmin_report_17_month_option()
        reports.enter_reports_superAdmin_report_17_year()
        reports.enter_reports_superAdmin_report_17_year_option()
        reports.enter_reports_superAdmin_report_17_graph()
        reports.enter_reports_superAdmin_report_17_graph()
        reports.enter_reports_superAdmin_report_17_fund()
        sleep(1)
        reports.enter_reports_superAdmin_report_17_fund_result()
        reports.enter_reports_superAdmin_report_17_fund()
        reports.enter_reports_superAdmin_value_report_18()
        reports.enter_reports_superAdmin_report_18_month()
        # reports.enter_reports_superAdmin_report_18_month_option()
        reports.enter_reports_superAdmin_report_18_year()
        reports.enter_reports_superAdmin_report_18_year_option()
        reports.enter_reports_superAdmin_report_18_graph()
        reports.enter_reports_superAdmin_report_18_graph()
        reports.enter_reports_superAdmin_report_18_fund()
        sleep(1)
        reports.enter_reports_superAdmin_report_18_fund_result()
        reports.enter_reports_superAdmin_report_18_fund()
        reports.enter_reports_superAdmin_value_report_19()
        reports.enter_reports_superAdmin_report_19_month()
        # reports.enter_reports_superAdmin_report_19_month_option()
        reports.enter_reports_superAdmin_report_19_year()
        reports.enter_reports_superAdmin_report_19_year_option()
        reports.enter_reports_superAdmin_report_19_graph()
        reports.enter_reports_superAdmin_report_19_graph()
        reports.enter_reports_superAdmin_report_19_fund()
        sleep(1)
        reports.enter_reports_superAdmin_report_19_fund_result()
        reports.enter_reports_superAdmin_report_19_fund()
        reports.enter_reports_superAdmin_value_report_20()
        reports.enter_reports_superAdmin_report_20_month()
        # reports.enter_reports_superAdmin_report_20_month_option()
        reports.enter_reports_superAdmin_report_20_year()
        reports.enter_reports_superAdmin_report_20_year_option()
        reports.enter_reports_superAdmin_report_20_graph()
        reports.enter_reports_superAdmin_report_20_graph()
        reports.enter_reports_superAdmin_report_20_fund()
        sleep(1)
        reports.enter_reports_superAdmin_report_20_fund_result()
        reports.enter_reports_superAdmin_report_20_fund()
        reports.enter_reports_superAdmin_value_report_21()
        reports.enter_reports_superAdmin_report_21_month()
        # reports.enter_reports_superAdmin_report_21_month_option()
        reports.enter_reports_superAdmin_report_21_year()
        reports.enter_reports_superAdmin_report_21_year_option()
        reports.enter_reports_superAdmin_report_21_graph()
        reports.enter_reports_superAdmin_report_21_graph()
        reports.enter_reports_superAdmin_report_21_fund()
        sleep(1)
        reports.enter_reports_superAdmin_report_21_fund_result()
        reports.enter_reports_superAdmin_report_21_fund()
        reports.enter_reports_superAdmin_value_report_22()
        reports.enter_reports_superAdmin_report_22_month()
        # reports.enter_reports_superAdmin_report_22_month_option()
        reports.enter_reports_superAdmin_report_22_year()
        reports.enter_reports_superAdmin_report_22_year_option()
        reports.enter_reports_superAdmin_report_22_graph()
        reports.enter_reports_superAdmin_report_22_graph()
        reports.enter_reports_superAdmin_report_22_fund()
        sleep(1)
        reports.enter_reports_superAdmin_report_22_fund_result()
        reports.enter_reports_superAdmin_report_22_fund()

    @classmethod
    def tearDownClass(cls) -> None:
        sleep(5)
        cls.driver.close()
        cls.driver.quit()
