from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from time import sleep
from selenium.webdriver.chrome.options import Options

from Locators import*
from Pages.Login import LoginPage
from Pages.Settings import Settings
from Pages.Find_Element import FindElement

import unittest

# o = Options()
# o.add_argument('--no-sandbox')
#
# s = Service('d:\chromedriver_win32\chromedriver.exe')
driver = webdriver.Chrome(ChromeDriverManager().install())
# driver = webdriver.Chrome(executable_path="E:\PRG_Test\Pinvest_Admin\chromedriver.exe")


class Test_Pinvest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.driver = driver
        # cls.driver = webdriver.Chrome(service=s, options=o)
        cls.driver.maximize_window()
        cls.driver.implicitly_wait(15)

    def test01_login_register(self):
        self.driver.get("https://admin-ha1.pinvest.ir/signin")
        login = LoginPage(driver=self.driver)
        login.enter_username("superadmin")
        login.enter_password("1234kaKA!")
        login.enter_show_password()
        login.enter_btn_submit()
        sleep(3)
        login.enter_site_header()
        # login.enter_logout()
        # login.enter_logout_no()
        # login.enter_logout()
        # login.enter_logout_yes()

# # # settings

    def test02_settings(self):
        settings = Settings(driver=self.driver)
        findel = FindElement(driver=self.driver)
        findel.wait_until_element_has_an_attribute('xpath', click_settings, 'href', 'settings')
        # settings.enter_click_settings()
    #     ##assert settings
        settings.enter_settings_add()
        settings.enter_settings_name("aa")
        settings.enter_settings_trans("aa")
        settings.enter_settings_add_config_form("2")
        settings.enter_settings_value()
        settings.enter_settings_value_option()
        # settings.enter_settings_save()
        settings.enter_settings_no_save()
        print("تمام المان های اضافه کردن تنضیمات بررسی شد.")

    def test03_settings(self):
        settings= Settings(driver=self.driver)
        findel = FindElement(driver=self.driver)
        settings.enter_settings_version()
        settings.enter_settings_version_option()
        settings.enter_settings_transactions_daily()
        settings.enter_settings_transactions_daily_option()
        settings.enter_settings_transactions_monthly()
        settings.enter_settings_transactions_monthly_option()
        settings.enter_settings_FARABOOM_PAYMAN_API_MAX_CONTRACT_EXPIRATION_YEARS()
        settings.enter_settings_FARABOOM_PAYMAN_API_MAX_CONTRACT_EXPIRATION_YEARS_option()
        settings.enter_settings_POD_API_MAX_COUNT()
        settings.enter_settings_POD_API_MAX_COUNT_option()
        settings.enter_settings_FINNOTECH_API_MAX_MONTHLY_TRANSACTION_COUNT()
        settings.enter_settings_FINNOTECH_API_MAX_MONTHLY_TRANSACTION_COUNT_option()
        # settings.enter_settings_CAPTCHA()
        findel.wait_until_element_has_an_attribute('xpath', settings_CAPTCHA, 'name', 'CAPTCHA')
        settings.enter_settings_CAPTCHA_option()
        findel.wait_until_element_has_an_attribute('xpath', settings_SMS_PANEL, 'name', 'SMS_PANEL')
        # settings.enter_settings_SMS_PANEL()
        settings.enter_settings_SMS_PANEL_option()
        findel.wait_until_element_has_an_attribute('xpath', settings_OTP_EXPIRE, 'name', 'OTP_EXPIRE')
        # settings.enter_settings_OTP_EXPIRE()
        settings.enter_settings_OTP_EXPIRE_option()
        findel.wait_until_element_has_an_attribute('xpath', settings_TEST_MODE, 'name', 'TEST_MODE')
        findel.wait_until_element_has_an_attribute('xpath', settings_TEST_MODE, 'name', 'TEST_MODE')
        # settings.enter_settings_TEST_MODE()
        findel.wait_until_element_has_an_attribute('xpath', settings_MAX_OTP_CHECK, 'name', 'MAX_OTP_CHECK')
        # settings.enter_settings_MAX_OTP_CHECK()
        settings.enter_settings_MAX_OTP_CHECK_option()
        findel.wait_until_element_has_an_attribute('xpath', settings_TIME_SCOPE_EXPIRE, 'name', 'TIME_SCOPE_EXPIRE')
        # settings.enter_settings_TIME_SCOPE_EXPIRE()
        settings.enter_settings_TIME_SCOPE_EXPIRE_option()
        findel.wait_until_element_has_an_attribute('xpath', settings_LOGIN_TIME_EXPIRE, 'name', 'LOGIN_TIME_EXPIRE')
        # settings.enter_settings_LOGIN_TIME_EXPIRE()
        settings.enter_settings_LOGIN_TIME_EXPIRE_option()
        findel.wait_until_element_has_an_attribute('xpath', settings_MAX_RETRY_SCOPE, 'name', 'MAX_RETRY_SCOPE')
        # settings.enter_settings_MAX_RETRY_SCOPE()
        settings.enter_settings_MAX_RETRY_SCOPE_option()
        findel.wait_until_element_has_an_attribute('xpath', settings_GOOGLE_CAPTCHA_PAGES, 'name', 'GOOGLE_CAPTCHA_PAGES')
        findel.wait_until_element_has_an_attribute('xpath', settings_GOOGLE_CAPTCHA_PAGES, 'name', 'GOOGLE_CAPTCHA_PAGES')
        # settings.enter_settings_GOOGLE_CAPTCHA_PAGES()
        findel.wait_until_element_has_an_attribute('xpath', settings_REQUIREMENT_BANK_ACCOUNT_REGISTRATION, 'name', 'REQUIREMENT_BANK_ACCOUNT_REGISTRATION')
        findel.wait_until_element_has_an_attribute('xpath', settings_REQUIREMENT_BANK_ACCOUNT_REGISTRATION, 'name', 'REQUIREMENT_BANK_ACCOUNT_REGISTRATION')
        # settings.enter_settings_REQUIREMENT_BANK_ACCOUNT_REGISTRATION()
        findel.wait_until_element_has_an_attribute('xpath', settings_INCREASE_COEFFICIENT, 'name', 'INCREASE_COEFFICIENT')
        # settings.enter_settings_INCREASE_COEFFICIENT()
        settings.enter_settings_INCREASE_COEFFICIENT_option()
        findel.wait_until_element_has_an_attribute('xpath', settings_GOOGLE_2F_AUTH, 'name', 'GOOGLE_2F_AUTH')
        findel.wait_until_element_has_an_attribute('xpath', settings_GOOGLE_2F_AUTH, 'name', 'GOOGLE_2F_AUTH')
        # settings.enter_settings_GOOGLE_2F_AUTH()
        findel.wait_until_element_has_an_attribute('xpath', settings_WRAPPER_SEND_MESSAGE_BY_SMS, 'name', 'WRAPPER_SEND_MESSAGE_BY_SMS')
        # settings.enter_settings_WRAPPER_SEND_MESSAGE_BY_SMS()
        settings.enter_settings_WRAPPER_SEND_MESSAGE_BY_SMS_option()
        findel.wait_until_element_has_an_attribute('xpath', settings_WRAPPER_SEND_PATTERN_BY_SMS, 'name', 'WRAPPER_SEND_PATTERN_BY_SMS')
        # settings.enter_settings_WRAPPER_SEND_PATTERN_BY_SMS()
        settings.enter_settings_WRAPPER_SEND_PATTERN_BY_SMS_option()
        findel.wait_until_element_has_an_attribute('xpath', settings_SHAHKAR_PANEL, 'name', 'SHAHKAR_PANEL')
        # settings.enter_settings_SHAHKAR_PANEL()
        settings.enter_settings_SHAHKAR_PANEL_option()
        findel.wait_until_element_has_an_attribute('xpath', settings_WRAPPER_SHAHKAR, 'name', 'WRAPPER_SHAHKAR')
        # settings.enter_settings_WRAPPER_SHAHKAR()
        settings.enter_settings_WRAPPER_SHAHKAR_option()
        findel.wait_until_element_has_an_attribute('xpath', settings_IPG_JIBIMO_CHECK_NATIONAL_CODE, 'name', 'IPG_JIBIMO_CHECK_NATIONAL_CODE')
        findel.wait_until_element_has_an_attribute('xpath', settings_IPG_JIBIMO_CHECK_NATIONAL_CODE, 'name', 'IPG_JIBIMO_CHECK_NATIONAL_CODE')
        # settings.enter_settings_IPG_JIBIMO_CHECK_NATIONAL_CODE()
        findel.wait_until_element_has_an_attribute('xpath', settings_CARD_SERVICE_MENU, 'name', 'CARD_SERVICE_MENU')
        # settings.enter_settings_CARD_SERVICE_MENU()
        settings.enter_settings_CARD_SERVICE_MENU_option()
        findel.wait_until_element_has_an_attribute('xpath', settings_RAYAN_REQUEST_TIMEOUT, 'name', 'RAYAN_REQUEST_TIMEOUT')
        # settings.enter_settings_RAYAN_REQUEST_TIMEOUT()
        settings.enter_settings_RAYAN_REQUEST_TIMEOUT_option()
        findel.wait_until_element_has_an_attribute('xpath', settings_DOMAIN_SEND_SMS, 'name', 'DOMAIN_SEND_SMS')
        # settings.enter_settings_DOMAIN_SEND_SMS()
        settings.enter_settings_DOMAIN_SEND_SMS_option()
        findel.wait_until_element_has_an_attribute('xpath', settings_MIN_NAV, 'name', 'MIN_NAV')
        # settings.enter_settings_MIN_NAV()
        settings.enter_settings_MIN_NAV_option()
        findel.wait_until_element_has_an_attribute('xpath', settings_MAX_NAV, 'name', 'MAX_NAV')
        # settings.enter_settings_MAX_NAV()
        settings.enter_settings_MAX_NAV_option()
        findel.wait_until_element_has_an_attribute('xpath', settings_SEJAM_DEFAULT, 'name', 'SEJAM_DEFAULT')
        # settings.enter_settings_SEJAM_DEFAULT()
        settings.enter_settings_SEJAM_DEFAULT_option()
        findel.wait_until_element_has_an_attribute('xpath', settings_WRAPPER_SEJAM, 'name', 'WRAPPER_SEJAM')
        # settings.enter_settings_WRAPPER_SEJAM()
        settings.enter_settings_WRAPPER_SEJAM_option()
        findel.wait_until_element_has_an_attribute('xpath', settings_WRAPPER_FUND_REGISTER, 'name', 'WRAPPER_FUND_REGISTER')
        # settings.enter_settings_WRAPPER_FUND_REGISTER()
        settings.enter_settings_WRAPPER_FUND_REGISTER_option()
        findel.wait_until_element_has_an_attribute('xpath', settings_IPG_SEP, 'name', 'IPG_SEP')
        findel.wait_until_element_has_an_attribute('xpath', settings_IPG_SEP, 'name', 'IPG_SEP')
        # settings.enter_settings_IPG_SEP()
        findel.wait_until_element_has_an_attribute('xpath', settings_IPG_PEP, 'name', 'IPG_PEP')
        findel.wait_until_element_has_an_attribute('xpath', settings_IPG_PEP, 'name', 'IPG_PEP')
        # settings.enter_settings_IPG_PEP()
        findel.wait_until_element_has_an_attribute('xpath', settings_EXPIRE_FUND_LICENSE_AFTER_DAY, 'name', 'EXPIRE_FUND_LICENSE_AFTER_DAY')
        settings.enter_settings_EXPIRE_FUND_LICENSE_AFTER_DAY()
        settings.enter_settings_EXPIRE_FUND_LICENSE_AFTER_DAY_option()
        findel.wait_until_element_has_an_attribute('xpath', settings_PROFIT_CALCULATION_DAY, 'name', 'PROFIT_CALCULATION_DAY')
        # settings.enter_settings_PROFIT_CALCULATION_DAY()
        settings.enter_settings_PROFIT_CALCULATION_DAY_option()
        findel.wait_until_element_has_an_attribute('xpath', settings_IPG_SEPEHR, 'name', 'IPG_SEPEHR')
        findel.wait_until_element_has_an_attribute('xpath', settings_IPG_SEPEHR, 'name', 'IPG_SEPEHR')
        # settings.enter_settings_IPG_SEPEHR()
        findel.wait_until_element_has_an_attribute('xpath', settings_PAYMENT_LINK_GATEWAY, 'name', 'PAYMENT_LINK_GATEWAY')
        # settings.enter_settings_PAYMENT_LINK_GATEWAY()
        settings.enter_settings_PAYMENT_LINK_GATEWAY_option()
        findel.wait_until_element_has_an_attribute('xpath', settings_IPG_JIBIMO, 'name', 'IPG_JIBIMO')
        findel.wait_until_element_has_an_attribute('xpath', settings_IPG_JIBIMO, 'name', 'IPG_JIBIMO')
        # settings.enter_settings_IPG_JIBIMO()
        findel.wait_until_element_has_an_attribute('xpath', settings_BASE_NAV, 'name', 'BASE_NAV')
        # settings.enter_settings_BASE_NAV()
        settings.enter_settings_BASE_NAV_option()
        findel.wait_until_element_has_an_attribute('xpath', settings_IPG_SADAD, 'name', 'IPG_SADAD')
        findel.wait_until_element_has_an_attribute('xpath', settings_IPG_SADAD, 'name', 'IPG_SADAD')
        # settings.enter_settings_IPG_SADAD()
        print("تمام المان های ویرایش کردن تنضیمات بررسی شد.")


    @classmethod
    def tearDownClass(cls) -> None:
        sleep(5)
        cls.driver.close()
        cls.driver.quit()
